baseURL = "http://www.peteredewitt.com/"
languageCode = "en-us"
title = "Peter E. DeWitt, Ph.D."
theme = "ananke"

SectionPagesMenu = "main"
enableRobotsTXT = true
google_analytics = 'UA-87261307-1'
Paginate = 3


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Peter DeWitt"
  description = "Bio statistician, R Enthusiast"
  favicon = "/images/dewittpe_headshot_20160131.jpg"
  twitter = "https://twitter.com/Statistics4All"
  github  = "https://github.com/dewittpe"
  featured_image = "/images/maxresdefault.jpg"


